server:
  applicationConnectors:
    - type: http
      port: 8083
  adminConnectors:
    - type: http
      port: 8084

logging:
  level: INFO
  loggers:
    com.legendatours: TRACE

database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: qweqweQWE123!
  url: jdbc:postgresql://localhost/backoffice
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* Health Check */ SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
